# Generated by Django 3.2.11 on 2023-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
