# Generated by Django 3.2.11 on 2023-08-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('episode', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='number',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='videoId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='video.videoinfo'),
            preserve_default=False,
        ),
    ]
